### ISSUE TITLE
UPDATE_ROLLBACK_COMPLETE color

### ISSUE THREAD

**Issue by atkinsonm** [taimos/cfn-tail#9]
`UPDATE_ROLLBACK_COMPLETE` is red in the new console but displays as green in this script.

![image](https://user-images.githubusercontent.com/3342243/60901664-5340bd80-a23c-11e9-98b2-4a325ac86986.png)

![image](https://user-images.githubusercontent.com/3342243/60901678-5b006200-a23c-11e9-9bc0-f77ea46f64b8.png)

**Comment by atkinsonm** [comment]
The same is true for `ROLLBACK_COMPLETE`

![image](https://user-images.githubusercontent.com/3342243/60901909-be8a8f80-a23c-11e9-92dc-3bb196a44a98.png)

**Comment by hoegertn** [comment]
Would you be able to create a PR for this? Otherwise, I will see when I find the time.

**Comment by atkinsonm** [comment]
PR submitted
